1357 grouping strategy fails with large mismatch in sizes
nf-core/sarek pull request #1364
Opened 2023-12-20 17:48 UTC by adamrtalbot

- Split FASTQs are grouped earlier for more reliable grouping strategy
- Minimum number of fastqs for split_fastq is now 250

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/sarek _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2023-12-20 18:10 UTC, maxulysse approved these changes
LGTM

2023-12-20 18:10 UTC, maxulysse commented on workflows/sarek.nf
> +        reads_grouping_key.view()
We can remove that

2023-12-20 18:11 UTC, maxulysse commented
Can you update changelog too?

2023-12-20 18:15 UTC, FriederikeHanssen commented
Testing might be good, but that data probably can't be added to the modules repo, right?

2023-12-20 18:22 UTC, FriederikeHanssen requested changes

2023-12-20 18:22 UTC, FriederikeHanssen commented on nextflow_schema.json
> +                    "minimum": 250
this will disable the ability to turn of splitting. Currently, if 0 is set, no splitting is done

2023-12-21 09:47 UTC, FriederikeHanssen commented on nextflow_schema.json
> +                    "minimum": 250
agreed

2023-12-21 18:29 UTC, FriederikeHanssen approved these changes
🚀 😍

2023-12-21 18:29 UTC, FriederikeHanssen commented on workflows/sarek.nf
> +        bai_mapped = FASTQ_ALIGN_BWAMEM_MEM2_DRAGMAP_SENTIEON.out.bai
Bai at only  produced/tested with sentieon, but since it is the same, should work

2023-12-21 18:38 UTC, merged