added indexcov : finding large INDEL using the BAI index
nf-core/sarek pull request #1613
Opened 2024-08-05 19:58 UTC by lindenb

original discussion: https://nfcore.slack.com/archives/C05V9FRJYMV/p1722884937141779?thread_ts=1696933327.769139&cid=C05V9FRJYMV

> OK all, here I am one year later. I had the time to look at this code ! Let me remind you: goleft/indexcov can be used to fiind large INDEL using the BAI index.I've just implemented this in sarek and on my side I would be ready to submit a PR but I suppose some things needs to be fixed.

* i added the  `nf-core/goleft/indexcov module`
* "indexcov" is now allowed in 'params.tools'
* the subworkflow is in .`/subworkflows/local/bam_variant_calling_indexcov/main.nf`
the documentation as been brefly updated
* I created a local process used to generate a BAI with no unmapped,duplicate, etc...  `(./subworkflows/local/bam_variant_calling_indexcov/main.nf`)
* indexcov is only called for the **germline** worklfow, I don't have any experience with somatic/tumor WGS.
* test are missing, I don't know what I should write. However, `nf-test test tests/ --verbose --profile +singularity` works
* new config file `./conf/modules/indexcov.config`

## PR checklist

- [X] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [X] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/sarek _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [X] Make sure your code lints (`nf-core lint`): Too many warnings but nothing related to 'indexcov'
- [x] Ensure the test suite passes (`nf-test test tests/ --verbose --profile +docker`).
- [x] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [?] `CHANGELOG.md` is updated (I'm not sure how to set this without a PR hash...)
- [x] `README.md` is updated (including new tool citations and authors/contributors).

2024-08-05 20:21 UTC, lindenb commented
OK, I merged into `dev`, let's re-run my tests...

2024-08-06 11:17 UTC, asp8200 commented
> I think it ok now, nevertheless there is still a pre-commit error but I don't understand the error.

prettier is complaining about the following files:
```
docs/output.md
modules.json
README.md
docs/usage.md
```

2024-08-06 12:01 UTC, lindenb commented
@asp8200 Thanks, yes I saw this, but was is the error exactly ?

2024-08-06 14:54 UTC, asp8200 commented
You can run `prettier` locally on your branch on those above-mentioned files. However, it might also be possible to have a github-action fix it for you. Let's try...

nf-core-bot fix linting

2024-08-06 14:55 UTC, asp8200 commented
@nf-core-bot fix linting

2024-08-30 15:19 UTC, maxulysse commented on README.md
> +- [Pierre Lindenbaum]https://github.com/lindenb=
```suggestion
- [Pierre Lindenbaum](https://github.com/lindenb)
```

2024-08-30 15:21 UTC, maxulysse commented on modules/local/indexcov/main.nf
I would put this in `samtools/reindex_bam` instead of `indexcov`

2024-08-30 15:22 UTC, maxulysse commented on subworkflows/local/bam_variant_calling_indexcov/main.nf
> +
I'd say it'd be nice to emit outputs from indexcov

2024-08-30 15:47 UTC, lindenb commented
@maxulysse thank you for the review Maxime, I'm currently away from my code, I'll try to have a look at this next week.

Q: this should be set for WGS calling only, what would be the best way/place to set this test ?
Q: should I put this test into the somatic workflow too ? where ?

2024-08-30 16:17 UTC, maxulysse commented
> @maxulysse thank you for the review Maxime, I'm currently away from my code, I'll try to have a look at this next week.

No worries, I know days can be busy

> Q: this should be set for WGS calling only, what would be the best way/place to set this test ?
> Q: should I put this test into the somatic workflow too ? where ?

I think I would just allow for it if not using the params.wes, so maybe a message in case tool is used with params, similarly to what we do with other warning messages.
And then I'd say adding this test when calling the variant_calling subworkflows.

2024-09-03 11:59 UTC, lindenb commented
@maxulysse back to you, thanks !

2024-09-03 12:54 UTC, maxulysse commented on docs/output.md
> +  scaled coverage for that sample in that 16KB chunk.
```suggestion
#### indexcov

[indexcov](https://github.com/brentp/goleft/tree/master/indexcov) quickly estimate coverage from a whole-genome bam or cram index.
A bam index has 16KB resolution and it is used as a coverage estimate .
The output is scaled to around 1. So a long stretch with values of 1.5 would be a heterozygous duplication. This is useful as a quick QC to get coverage values across the genome.

**Output directory: `{outdir}/variantcalling/indexcov/`**

In addition to the interactive HTML files, `indexcov` outputs a number of text files:

- `<sample>-indexcov.ped`: a .ped/.fam file with the inferred sex in the appropriate column if the sex chromosomes were found.
  the CNX and CNY columns indicating the floating-point estimate of copy-number for those chromosomes.
  `bins.out`: how many bins had a coverage value outside of (0.85, 1.15). high values can indicate high-bias samples.
  `bins.lo`: number of bins with value < 0.15. high values indicate missing data.
  `bins.hi`: number of bins with value > 1.15.
  `bins.in`: number of bins with value inside of (0.85, 1.15)
  `p.out`: `bins.out/bins.in`
  `PC1...PC5`: PCA projections calculated with depth of autosomes.

- `<sample>-indexcov.roc`: tab-delimited columns of chrom, scaled coverage cutoff, and $n_samples columns where each indicates the
  proportion of 16KB blocks at or above that scaled coverage value.
- `<sample>-indexcov.bed.gz`: a bed file with columns of chrom, start, end, and a column per sample where the values indicate there
  scaled coverage for that sample in that 16KB chunk.
```

2024-09-03 12:54 UTC, maxulysse commented on docs/usage.md
> +| [Indexcov](https://github.com/brentp/goleft/tree/master/indexcov)                                       |  x  |  -  |   -    |    -    |   -   |    x    |
```suggestion
| [indexcov](https://github.com/brentp/goleft/tree/master/indexcov)                                       |  x  |  -  |   x    |    x    |   x   |    x    |
| [TIDDIT](https://github.com/SciLifeLab/TIDDIT)                                                          |  x  |  x  |   x    |    x    |   x   |    x    |
| [ASCAT](https://github.com/VanLoo-lab/ascat)                                                            |  x  |  x  |   -    |    -    |   -   |    x    |
| [CNVKit](https://cnvkit.readthedocs.io/en/stable/)                                                      |  x  |  x  |   -    |    x    |   x   |    x    |
| [Control-FREEC](https://github.com/BoevaLab/FREEC)                                                      |  x  |  x  |   x    |    -    |   x   |    x    |
| [MSIsensorPro](https://github.com/xjtu-omics/msisensor-pro)                                             |  x  |  x  |   x    |    -    |   -   |    x    |
| [indexcov](https://github.com/brentp/goleft/tree/master/indexcov)                                       |  x  |  -  |   -    |    -    |   -   |    x    |
```

2024-09-03 12:59 UTC, maxulysse commented
Just some minor comments

2024-09-03 13:39 UTC, maxulysse commented
@lindenb you know you can batch commit all suggestions from the `Files Changed` tab?

2024-09-03 13:43 UTC, lindenb commented
@maxulysse  I know now :-P

2024-09-13 08:11 UTC, maxulysse commented on modules/local/samtools/reindex_bam/environment.yml
> +  - defaults
```suggestion
```

2024-09-13 08:12 UTC, maxulysse commented on CHANGELOG.md
> +- [#1613](https://github.com/nf-core/sarek/pull/1613) - add indexcov
Can you move this line in the current dev section?

2024-12-10 09:12 UTC, FriederikeHanssen commented on modules/local/samtools/reindex_bam/main.nf
> +    tuple val(meta), path("${meta.id}.reindex.bam"), path("${meta.id}.reindex.bam.bai"),emit: output
Looks like indexcov is also supporting CRAM files. Is there a reason to first convert them to bam here and not use also CRAM?

2024-12-10 09:40 UTC, FriederikeHanssen commented on modules/local/samtools/reindex_bam/main.nf
> +    tuple val(meta), path("${meta.id}.reindex.bam"), path("${meta.id}.reindex.bam.bai"),emit: output
Oh sorry missed that.  merging this then now.

2024-12-10 10:38 UTC, FriederikeHanssen commented on docs/usage.md
> +| [indexcov](https://github.com/brentp/goleft/tree/master/indexcov)                                       |  x  |  -  |   -    |    -    |   -   |    x    |
```suggestion
```

2024-12-10 10:39 UTC, FriederikeHanssen commented on docs/usage.md
> +| [indexcov](https://github.com/brentp/goleft/tree/master/indexcov)                                       |  x  |  -  |   x    |    x    |   x   |    x    |
```suggestion
| [indexcov](https://github.com/brentp/goleft/tree/master/indexcov)                                       |  x  |  -  |   x    |    x    |   -   |    x    |
```

2024-12-10 10:47 UTC, FriederikeHanssen commented on docs/usage.md
> +| [indexcov](https://github.com/brentp/goleft/tree/master/indexcov)                                       |  x  |  -  |   x    |    x    |   x   |    x    |
@lindenb From the code it looks like tumor-only is currently not covered. Would remove it here for now

2024-12-10 11:08 UTC, FriederikeHanssen commented
@nf-core-bot fix linting

2024-12-10 11:52 UTC, FriederikeHanssen commented on docs/usage.md
> +| [indexcov](https://github.com/brentp/goleft/tree/master/indexcov)                                       |  x  |  -  |   x    |    x    |   x   |    x    |
Going to push this. Need to beat the tools release. Ain't nobody got time for a template update :D

2024-12-10 11:52 UTC, FriederikeHanssen commented on docs/usage.md
> +| [indexcov](https://github.com/brentp/goleft/tree/master/indexcov)                                       |  x  |  -  |   x    |     x     |     x      |           x            |
```suggestion
| [indexcov](https://github.com/brentp/goleft/tree/master/indexcov)                                       |  x  |  -  |   -    |     x     |     -      |           x            |
```

2024-12-10 11:57 UTC, maxulysse commented on modules/local/samtools/reindex_bam/environment.yml
> +name: samtools_view
```suggestion
```

2024-12-10 11:57 UTC, maxulysse commented on modules/nf-core/goleft/indexcov/environment.yml
> +name: goleft_indexcov
```suggestion
```

2024-12-10 11:57 UTC, maxulysse commented on modules/nf-core/goleft/indexcov/environment.yml
> +name: goleft_indexcov
this one is probably out of date

2024-12-10 11:59 UTC, maxulysse commented on subworkflows/local/bam_variant_calling_somatic_all/main.nf
>      out_msisensorpro
TODO: have the same scheme for output
ie: either `out_` or `_output`

2024-12-10 12:25 UTC, maxulysse requested changes
sarek_subway.{png,svg} should be in docs/images

2024-12-10 12:28 UTC, maxulysse submitted a review, later dismissed

2024-12-10 13:35 UTC, maxulysse approved these changes

2024-12-10 13:35 UTC, merged