Fixes bug
nf-core/sarek pull request #1624
Opened 2024-08-16 02:21 UTC by bounlu

Fixes https://github.com/nf-core/sarek/issues/1622

2024-08-16 07:40 UTC, FriederikeHanssen requested changes
Can you upadte the Changelog please?

2024-08-16 09:44 UTC, maxulysse commented
good catch

2024-11-15 21:11 UTC, maxulysse approved these changes

2024-11-17 12:35 UTC, maxulysse approved these changes

2024-11-17 12:36 UTC, merged