ci: Skip nf-test on docs changes
nf-core/sarek pull request #1761
Opened 2024-12-12 12:56 UTC by edmundmiller

Skips nf-test on any docs changes.

We can probably cut `docs/**` if we want to save lines 🙃

2024-12-12 13:08 UTC, maxulysse commented on .github/workflows/ci.yml
> +      - "**/*.md"
```suggestion
    paths-ignore:
      - "docs/**"
      - "**/*.md"
      - "**/*.png"
      - "**/*.svg"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**/*.md"
      - "**/*.png"
      - "**/*.svg"
```

2024-12-12 19:41 UTC, jfy133 commented
The tests still ran though, no?

2024-12-12 21:54 UTC, edmundmiller commented
> The tests still ran though, no?

This modified a GitHub action yml not a doc 😜

2024-12-13 05:04 UTC, jfy133 commented
> > The tests still ran though, no?
> 
> This modified a GitHub action yml not a doc 😜 

Oh haha fair, but maybe worth modifying a doc as a test? 😬

2025-02-24 18:27 UTC, maxulysse requested changes
CHANGELOG?

2025-02-24 23:23 UTC, edmundmiller commented
First, happy to update it. 

But that request brought up a bigger question for me. 

IMO the CI change doesn't affect end users. Most developers aren't going to notice this one. 

Almost feels like we need a separate changelog or developers or call the git log good enough. 

I personally vote we don't update the changelog unless it's changing the user experience. Didn't flags, different tools so expect a different result.

2025-02-25 11:41 UTC, maxulysse approved these changes

2025-02-25 11:41 UTC, merged

2025-02-25 14:59 UTC, mashehu commented
nuh, these kind of DX related changes shouldn't occur so often and don't really fill up the changelog, so better to add it there then to never mention it 🙂 (also might help other devs to discover these changes)