update to include intervals
nf-core/sarek pull request #708
Opened 2022-08-17 14:49 UTC by nickhsmith

Update the nf-core `samtools/mpileup` module to include the changes to interval handling

2022-08-17 15:58 UTC, asp8200 approved these changes
Looks fine to me.

As you may have noticed, there is one failing test, but - as far as I can tell - that is just a test which detects that this PR is going to `master` and not to `dev` as would normally be the case.

2022-08-18 08:26 UTC, FriederikeHanssen requested changes
Nice! Thanks a lot, would you also update the changelog please? Make a new section with release 3.0.1 and add this PR.

2022-08-18 09:03 UTC, FriederikeHanssen approved these changes

2022-08-18 09:03 UTC, FriederikeHanssen commented
@nf-core-bot fix linting

2022-08-18 09:58 UTC, merged