replace local subworkflow with nf-core version - vcf_annotate_ensemblvep
nf-core/sarek pull request #865
Opened 2022-11-24 14:18 UTC by maxulysse

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/sarek _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2022-11-24 14:23 UTC, matthdsm approved these changes

2022-11-24 14:26 UTC, FriederikeHanssen requested changes

2022-11-24 14:26 UTC, FriederikeHanssen commented on modules.json
> +                        "git_sha": "6301e29d77e7ec7ce98b55b8a361b316a9a91bfe",
why is it mpileup checksum updated?

2022-11-24 14:27 UTC, FriederikeHanssen commented on subworkflows/nf-core/vcf_annotate_ensemblvep/main.nf
> -    ch_versions = ch_versions.mix(TABIX_BGZIPTABIX.out.versions.first())
ok so cleared up now to not use `.first()`?

2022-11-24 14:31 UTC, FriederikeHanssen commented on subworkflows/local/vcf_annotate_all/main.nf
> +include { VCF_ANNOTATE_ENSEMBLVEP as VCF_ANNOTATE_MERGE } from '../../nf-core/vcf_annotate_ensemblvep/main.nf'
can we continue to import without `.nf` for consistency sake

2022-11-25 13:51 UTC, maxulysse commented
@nf-core-bot fix linting pretty please :pray:

2022-11-25 13:52 UTC, FriederikeHanssen commented on modules.json
> +                            "modules"
prettier?

2022-11-25 13:53 UTC, FriederikeHanssen commented
the annotate.conf probably needs someupdating too since we rely on the naming there

2022-11-25 13:54 UTC, maxulysse commented
> the annotate.conf probably needs someupdating too since we rely on the naming there

Was planning to do so in a coming commit

2022-11-25 18:01 UTC, merged