Merging template updates 2.7.1
nf-core/sarek pull request #890
Opened 2022-12-09 11:52 UTC by FriederikeHanssen

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/sarek/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/sarek _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2022-12-09 11:53 UTC, FriederikeHanssen commented
@nf-core-bot fix linting please

2022-12-09 11:56 UTC, FriederikeHanssen commented
@nf-core-bot fix linting

2022-12-09 12:28 UTC, FriederikeHanssen commented on nextflow.config
> +    nextflowVersion = '!>=22.10.1'
```suggestion
    nextflowVersion = '!>=21.10.3'
```

2022-12-09 14:34 UTC, maxulysse commented on docs/usage.md
> +A first step to bypass this error, you could try to increase the amount of CPUs, memory, and time for the whole pipeline. Therefor you can try to increase the resource for the parameters `--max_cpus`
```suggestion
A first step to bypass this error, you could try to increase the amount of CPUs, memory, and time for the whole pipeline. Therefor you can try to increase the resource for the parameters `--max_cpus`, `--max_memory`, and `--max_time`. Based on the error above, you have to increase the amount of memory.
Therefore you can go to the [parameter documentation of sarek](https://nf-co.re/sarek/3.1.1/parameters) and scroll down to the `show hidden parameter` button to get the default value for `--max_memory`.
In this case 128GB, you than can try to run your pipeline again with `--max_memory 200GB -resume` to skip all process, that were already calculated.
If you can not increase the resource of the complete pipeline, you can try to adapt the resource for a single process as mentioned below.
```

2022-12-09 14:36 UTC, maxulysse requested changes
rnaseq -> sarek

2022-12-11 14:24 UTC, maxulysse approved these changes

2022-12-11 14:24 UTC, merged